services:
  app:
    build: .
    image: node:14
    ports:
      - "3000:3000"
    container_name: app-container
    working_dir: /code
    command: npm start
    environment:
      NODE_ENV: development
      MYSQL_URL: mariadb://app:wonderful@db:3306/miechallenge
      PORT: 3000
    networks:
      - board-game-network
    depends_on:
      - db
    volumes:
      - .:/code:delegated
      - /code/node_modules


  db:
    image: mariadb
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: wonderful
      MYSQL_DATABASE: miechallenge
    networks:
      - board-game-network
    volumes:
      - mariadb_data:/var/lib/mysql

networks:
  board-game-network:
    driver: bridge

volumes:
  mariadb_data:
